### ISSUE TITLE
DBの設計について

### ISSUE THREAD

**Issue by phythonSUMIRE** [ooitanojohn/IW31auction#27]
現状のDBの改善点として
user_tbl
・ユーザーidとログインidの違いが判らない（こちらは画面設計によるのかも？）
・郵便番号に-ごと格納しちゃうのか（これは画面設計しだい）
・論理削除にしたいためユーザーの状態を追加したい（許可はいただいた）

product_tbl
・car_conditionは何段階？何=何？なのか

koyaku_tbl(購入テーブル)
・購入テーブルをなくして入札テーブルに購入完了のフラグを入れる(ただし、入札テーブルがあったほうがわかりやすいとは思う)
・入札テーブルの主キーをuseridと入札時間に変更する。(ここにIDあっても検索で使わないと思う)

biddings_tbl(入札テーブル)
・定期的に削除処理を走らせてデータ量を削減するか

などを考えています。何か意見があればお願いします。

**Comment by ooitanojohn** [comment]
ログインID = ユーザーID も emailで統一
郵便番号はstringで-ごとでもサーバーに任せる とりあえず"000-0000"の形で渡す
下分からん 詳しい人求む

**Comment by ooitanojohn** [comment]
データ量とかは追加機能としてサーバー側でやってもらえれば

**Comment by ooitanojohn** [comment]
テーブル名は_tblを消す

**Comment by ooitanojohn** [comment]
DAOではひとまず結合しない単一テーブル一覧取得、IDをwhere句で絞る、新規登録、更新の4種類を記述してもらいます。

**Comment by ooitanojohn** [comment]
id以外で絞り込みをする場合indexを貼る必要があるかもとか
テーブル結合が必要なクエリがあるとかも確認したいです

**Comment by phythonSUMIRE** [comment]
carテーブルの項目はもう少し考えたほうがいいかもしれない。
車購入時の事についてもう少し考えたいと思います。

**Comment by ooitanojohn** [comment]
https://github.com/mysqljs/mysql#poolcluster
