### ISSUE TITLE
実行するSQLについて

### ISSUE THREAD

**Issue by phythonSUMIRE** [ooitanojohn/IW31auction#59]
実行するSQLというのはDAOに記述されうような実際に使用されるSQLということでしょうか。

**Comment by ooitanojohn** [comment]
そうですね
DAOではひとまず結合しない単一テーブル一覧取得、IDをwhere句で絞る、新規登録、更新の4種類を記述してもらいます。

**Comment by ooitanojohn** [comment]
id以外で絞り込みをする場合indexを貼る必要があるかもとか
テーブル結合が必要なクエリがあるとかも確認したいです

**Comment by ooitanojohn** [comment]
#27 にコメント

**Comment by ooitanojohn** [comment]
id以外で絞り込みをする場合indexを貼る必要があるかもとか
テーブル結合が必要なクエリがあるとかも確認したいです
