### ISSUE TITLE
car_tblにカラムの追加

### ISSUE THREAD

**Issue by phythonSUMIRE** [ooitanojohn/IW31auction#60]
車の名前だけでは細かい車種を記録するのは難しいためgradeというカラムを追加したいです。
それにあたって検索・商品登録などの際、車のgradeを入力(選択式などで)させてほしいです。

gradeの種類は
1=C(コンフォート) 
2=L(ラグジュアリ)
 3=R(レース) 
4=G(ジェネラル) 
5=GT(グランツーリスモ) 
6=S(スポーツ)
 7=D(ディーゼル) 
8=X(未知)
にしています。よろしくお願いします。

**Comment by ooitanojohn** [comment]
了解です、ありがとう

**Comment by phythonSUMIRE** [comment]
車の情報、少し少なすぎる気もするので検索に合わせて追加するかもです。

**Comment by ooitanojohn** [comment]
#27
